name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn package
          
      - name: Build Docker Image and Push
        run: |
           docker build -t gpavankumarreddy/dilipreddy:latest .
           echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u gpavankumarreddy --password-stdin
           docker push gpavankumarreddy/dilipreddy:latest


          # Create Docker configuration file
          echo '{"auths":{"https://index.docker.io/v1/":{"auth":"'$(echo -n ${{ secrets.DOCKERHUB_USERNAME }}:$DOCKERHUB_PASSWORD | base64 -w 0)'","email":"your-email@example.com"}}}' > $HOME/.docker/config.json
          
          sudo docker push gpavankumarreddy/dilipreddy:latest
