name: Maven Build and Docker Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn package
         
      - name: List Maven Build Output
        run: ls -R target

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Assuming your Dockerfile is in the root of your project
          file: Dockerfile
          push: true
          tags: gpavankumarreddy/helloworld:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Docker Container
        run: docker run -p 8081:8080 -d gpavankumarreddy/helloworld:latest
