name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: self-hosted  # Specify your self-hosted runner here

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn package

      - name: Build Docker Image
        run: |
          sudo docker build -t gpavankumarreddy/dilipreddy:latest .
          echo '{"auths":{"https://index.docker.io/v1/":{"auth":"'$(echo -n ${{ secrets.DOCKERHUB_USERNAME }}:$DOCKERHUB_PASSWORD | base64 -w 0)'","email":"gpavankumarreddy98@gmail.com"}}}' > $HOME/.docker/config.json
          sudo docker push gpavankumarreddy/dilipreddy:latest
