name: Maven Build and Run Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn package

      - name: List Maven Build Output
        run: ls -R target

      - name: Build Docker Image
        run: docker build -t gpavankumarreddy/helloworld:latest .

      - name: Run Docker Container
        run: docker run -p 8081:8080 -d gpavankumarreddy/helloworld:latest
        
      - name: LIST Container
        run: docker ps
