name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:  
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn package
          
      - name: Build Docker Image and Push
        run: |
           sudo docker build -t gpavankumarreddy/dilipreddy:latest .
           echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u gpavankumarreddy --password-stdin
           sudo docker push gpavankumarreddy/dilipreddy:latest
           sudo docker run -d -p 8081:8080 --name gpavan gpavankumarreddy/dilipreddy:latest

