name: Maven Build and Run Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted  # Use a self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn package

      - name: List Maven Build Output
        run: ls -R target

      - name: Build Docker Image
        run: sudo docker build -t gpavankumarreddy/helloworld:latest .

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8081 --name babu gpavankumarreddy/helloworld:latest
        
      - name: LIST Container
        run: sudo docker ps
